version: "3"

vars:
  DEV_DOT_ENV: .env.dev
  TESTING_DOT_ENV: .env.testing

tasks:
  init:
    cmds:
      - npm install
      - go mod tidy
  server-dev:
    dotenv: ["./configs/{{.DEV_DOT_ENV}}"]
    cmds:
      - air
  server-test-unit:
    dir: internal
    cmds:
      - go test ./... -v -short
  server-test-integration:
    dotenv: ["./configs/{{.TESTING_DOT_ENV}}"]
    cmds:
      - docker compose -p mangrove-integration-test-db -f ./configs/docker-compose.postgresdev.yaml up -d --wait
      - defer: docker compose -p mangrove-integration-test-db -f ./configs/docker-compose.postgresdev.yaml down
      - go run ./cmd/migrate/main.go
      - go test ./... -v -run Integration
  server-gen-mocks:
    dir: internal
    cmds:
      - go generate ./...
  migration-new:
    dir: tools
    cmds:
      - node migration_gen.js {{.CLI_ARGS}}
      - go fmt ../internal/migrations/migrations.go
  db-dev-up:
    dir: configs
    dotenv: ["{{.DEV_DOT_ENV}}"]
    cmds:
      - docker compose -p mangrove-db -f docker-compose.postgresdev.yaml up -d --wait
  db-dev-drop:
    dir: configs
    dotenv: ["{{.DEV_DOT_ENV}}"]
    cmds:
      - docker compose -p mangrove-db -f docker-compose.postgresdev.yaml down
  db-dev-stop:
    dir: configs
    dotenv: ["{{.DEV_DOT_ENV}}"]
    cmds:
      - docker compose -p mangrove-db -f docker-compose.postgresdev.yaml stop
  ui-main-dev:
    cmds:
      - npx vite web_src/main
  ui-main-build:
    cmds:
      - npx tsc
      - npx vite build web_src/main
  ui-main-preview:
    cmds:
      - npx vite preview web_src/main
  ui-init-dev:
    cmds:
      - npx vite web_src/init
  ui-init-build:
    cmds:
      - npx tsc
      - npx vite build web_src/init
  ui-init-preview:
    cmds:
      - npx vite preview web_src/init