version: "3"

vars:
  DEV_DOT_ENV: .env.dev

tasks:
  init:
    cmds:
      - npm install
      - go mod tidy
  server-dev:
    dotenv: ["./configs/{{.DEV_DOT_ENV}}"]
    cmds:
      - air
  migration-new:
    dir: tools
    cmds:
      - node migration_gen.js {{.CLI_ARGS}}
      - go fmt ../internal/migrations/migrations.go
  db-dev-up:
    dir: configs
    dotenv: ["{{.DEV_DOT_ENV}}"]
    cmds:
      - docker compose -p mangrove-db -f docker-compose.postgresdev.yaml up -d --wait
  db-dev-drop:
    dir: configs
    dotenv: ["{{.DEV_DOT_ENV}}"]
    cmds:
      - docker compose -p mangrove-db -f docker-compose.postgresdev.yaml down
  db-dev-stop:
    dir: configs
    dotenv: ["{{.DEV_DOT_ENV}}"]
    cmds:
      - docker compose -p mangrove-db -f docker-compose.postgresdev.yaml stop
  ui-dev:
    cmds:
      - npx vite
  ui-build:
    cmds:
      - npx tsc
      - npx vite build
  ui-preview:
    cmds:
      - npx vite preview
