// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/asatraitis/mangrove/internal/dal (interfaces: ClientsDAL)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_clientsDAL.go -package=mocks github.com/asatraitis/mangrove/internal/dal ClientsDAL
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/asatraitis/mangrove/internal/dal/models"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockClientsDAL is a mock of ClientsDAL interface.
type MockClientsDAL struct {
	ctrl     *gomock.Controller
	recorder *MockClientsDALMockRecorder
	isgomock struct{}
}

// MockClientsDALMockRecorder is the mock recorder for MockClientsDAL.
type MockClientsDALMockRecorder struct {
	mock *MockClientsDAL
}

// NewMockClientsDAL creates a new mock instance.
func NewMockClientsDAL(ctrl *gomock.Controller) *MockClientsDAL {
	mock := &MockClientsDAL{ctrl: ctrl}
	mock.recorder = &MockClientsDALMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientsDAL) EXPECT() *MockClientsDALMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClientsDAL) Create(arg0 pgx.Tx, arg1 *models.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockClientsDALMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClientsDAL)(nil).Create), arg0, arg1)
}
