// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/asatraitis/mangrove/internal/dal (interfaces: UserDAL)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_user.go -package=mocks github.com/asatraitis/mangrove/internal/dal UserDAL
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/asatraitis/mangrove/internal/dal/models"
	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockUserDAL is a mock of UserDAL interface.
type MockUserDAL struct {
	ctrl     *gomock.Controller
	recorder *MockUserDALMockRecorder
	isgomock struct{}
}

// MockUserDALMockRecorder is the mock recorder for MockUserDAL.
type MockUserDALMockRecorder struct {
	mock *MockUserDAL
}

// NewMockUserDAL creates a new mock instance.
func NewMockUserDAL(ctrl *gomock.Controller) *MockUserDAL {
	mock := &MockUserDAL{ctrl: ctrl}
	mock.recorder = &MockUserDALMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDAL) EXPECT() *MockUserDALMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserDAL) Create(arg0 pgx.Tx, arg1 *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserDALMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserDAL)(nil).Create), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockUserDAL) GetByID(arg0 uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserDALMockRecorder) GetByID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserDAL)(nil).GetByID), arg0)
}

// GetByIdWithCredentials mocks base method.
func (m *MockUserDAL) GetByIdWithCredentials(arg0 uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdWithCredentials", arg0)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdWithCredentials indicates an expected call of GetByIdWithCredentials.
func (mr *MockUserDALMockRecorder) GetByIdWithCredentials(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdWithCredentials", reflect.TypeOf((*MockUserDAL)(nil).GetByIdWithCredentials), arg0)
}

// GetByUsernameWithCredentials mocks base method.
func (m *MockUserDAL) GetByUsernameWithCredentials(arg0 string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsernameWithCredentials", arg0)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsernameWithCredentials indicates an expected call of GetByUsernameWithCredentials.
func (mr *MockUserDALMockRecorder) GetByUsernameWithCredentials(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsernameWithCredentials", reflect.TypeOf((*MockUserDAL)(nil).GetByUsernameWithCredentials), arg0)
}
