services:
  base-postgres:
    image: postgres:latest
    ports:
      - "${MANGROVE_POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 1s
      timeout: 10s
      retries: 10
    environment:
      POSTGRES_PASSWORD: ${MANGROVE_POSTGRES_PASSWORD:-postgres}
      GROVE_POSTGRES_PORT: ${MANGROVE_POSTGRES_PORT:-5432}
volumes:
  database: